CapstoneProject/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using SmartBreadcrumbs.Attributes;

namespace CapstoneProject.Controllers {

    [Authorize(Roles = "Admin")]
    public class AppRolesController : Controller {

        private readonly RoleManager<IdentityRole> _roleManager;

        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        //List all the roles created by Users
        [Breadcrumb("Roles Management")]
        public IActionResult Index() {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        [Breadcrumb("Create", FromAction ="Index", FromController = typeof(AppRolesController))]
        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole model) {
            //Avoid duplicate role
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult()) {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

CapstoneProject/Controllers/IngredientCategoryController.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using SmartBreadcrumbs.Attributes;
using System.Collections.Generic;

namespace CapstoneProject.Controllers {
    [Authorize(Roles = "Admin")]
    public class IngredientCategoryController : Controller {

        private readonly IIngredientCategoryRepository _ingredientCategoryRepository;

        public IngredientCategoryController(IIngredientCategoryRepository ingredientCategoryRepository) {
            _ingredientCategoryRepository = ingredientCategoryRepository;
        }

        [Breadcrumb("Ingredient Categories Management")]
        public IActionResult Index() {
            IEnumerable<IngredientCategory> objIngredientCategoryList = _ingredientCategoryRepository.GetIngredientCategories();
            return View(objIngredientCategoryList);
        }

        // GET
        [Breadcrumb("Create", FromAction = "Index", FromController = typeof(IngredientCategoryController))]
        public IActionResult Create() {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(IngredientCategory obj) {
            if (ModelState.IsValid) {
                _ingredientCategoryRepository.InsertIngredientCategory(obj);
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        [Breadcrumb("Edit", FromAction = "Index", FromController = typeof(IngredientCategoryController))]
        public IActionResult Edit(int? id) {
            if (id == null || id == 0) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient category was not found." });
            }
            var categoryFromDb = _ingredientCategoryRepository.GetIngredientCategoryById(id);
            if (categoryFromDb == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient category was not found." });
            }
            return View(categoryFromDb);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IngredientCategory obj) {
            if (ModelState.IsValid) {
                _ingredientCategoryRepository.UpdateIngredientCategory(obj);
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        [Breadcrumb("Delete", FromAction = "Index", FromController = typeof(IngredientCategoryController))]
        public IActionResult Delete(int? id) {
            if (id == null || id == 0) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient category was not found." });
            }
            var categoryFromDb = _ingredientCategoryRepository.GetIngredientCategoryById(id);
            if (categoryFromDb == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient category was not found." });
            }
            return View(categoryFromDb);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id) {
            var obj = _ingredientCategoryRepository.GetIngredientCategoryById(id);
            if (obj == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient category was not found." });
            }
            _ingredientCategoryRepository.DeleteIngredientCategory(obj);
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

CapstoneProject/Controllers/RecipeCategoryController.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using SmartBreadcrumbs.Attributes;
using System.Collections.Generic;

namespace CapstoneProject.Controllers {
    [Authorize(Roles = "Admin")]
    public class RecipeCategoryController : Controller {

        private readonly IRecipeCategoryRepository _recipeCategoryRepository;

        public RecipeCategoryController(IRecipeCategoryRepository recipeCategoryRepository) {
            _recipeCategoryRepository = recipeCategoryRepository;
        }

        [Breadcrumb("Recipe Categories Management")]
        public IActionResult Index() {
            IEnumerable<RecipeCategory> objRecipeCategoryList = _recipeCategoryRepository.GetRecipeCategories();
            return View(objRecipeCategoryList);
        }


        //GET
        [Breadcrumb("Create", FromAction = "Index", FromController = typeof(RecipeCategoryController))]
        public IActionResult Create() {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RecipeCategory obj) {
            if (ModelState.IsValid) {
                _recipeCategoryRepository.InsertRecipeCategory(obj);
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        [Breadcrumb("Edit", FromAction = "Index", FromController = typeof(RecipeCategoryController))]
        public IActionResult Edit(int? id) {
            if (id == null || id == 0) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe category was not found." });
            }
            var categoryFromDb = _recipeCategoryRepository.GetRecipeCategoryById(id);
            if (categoryFromDb == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe category was not found." });
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RecipeCategory obj) {
            if (ModelState.IsValid) {
                _recipeCategoryRepository.UpdateRecipeCategory(obj);
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        [Breadcrumb("Delete", FromAction = "Index", FromController = typeof(RecipeCategoryController))]
        public IActionResult Delete(int? id) {
            if (id == null || id == 0) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe category was not found." });
            }
            var categoryFromDb = _recipeCategoryRepository.GetRecipeCategoryById(id);

            if (categoryFromDb == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe category was not found." });
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id) {
            var obj = _recipeCategoryRepository.GetRecipeCategoryById(id);
            if (obj == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe category was not found." });
            }
            _recipeCategoryRepository.DeleteRecipeCategory(obj);
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

CapstoneProject/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Firebase.Auth;
using Firebase.Storage;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Formats.Webp;
using Microsoft.AspNetCore.WebUtilities;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using MailKit;
using System.Text.RegularExpressions;
using NuGet.Packaging;
using SmartBreadcrumbs.Attributes;
using Microsoft.AspNetCore.Identity;
using BusinessObjects.Models;
using Repositories;

namespace CapstoneProject.Controllers {


    [Authorize(Roles = "Admin")]
    public class RecipesController : Controller {
        private readonly UserManager<Account> _userManager;

        private readonly IRecipeRepository _recipeRepository;
        private readonly IRecipeCategoryRepository _recipeCategoryRepository;

        public static string ApiKey = "AIzaSyDIXdDdvo8NguMgxLvn4DWMNS-vXkUxoag";
        public static string Bucket = "cookez-cloud.appspot.com";
        public static string AuthEmail = "cookez.mail@gmail.com";
        public static string AuthPassword = "cookez";

        public RecipesController(UserManager<Account> userManager, IRecipeRepository recipeRepository, IRecipeCategoryRepository recipeCategoryRepository) {
            _userManager = userManager;
            _recipeRepository = recipeRepository;
            _recipeCategoryRepository = recipeCategoryRepository;
        }

        // GET/POST: Recipes
        [Breadcrumb("Recipes Management")]

        public IActionResult Index(int pg = 1) {
            var recipes = _recipeRepository.GetRecipes();

            const int pageSize = 10; 

            if (pg < 1)
                pg = 1;

            int recsCount = recipes.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = recipes.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data);
        }

        // GET: Recipes/Details/5
        public IActionResult Details(int? id) {

            if (id == null || _recipeRepository.GetRecipes() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            return View(recipe);
        }

        [Authorize]
        // GET: Recipes/Delete/5
        public IActionResult Delete(int? id) {
            if (id == null || _recipeRepository.GetRecipes() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            return View(recipe);
        }
        [Authorize]
        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (_recipeRepository.GetRecipes() == null) {
                return Problem("Entity set 'RecipeOrganizerContext.Recipes'  is null.");
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe != null) {
                if (recipe.ImgPath != null) {
                    await DeleteFromFirebaseStorage(recipe.ImgPath);
                }
                _recipeRepository.DeleteRecipe(recipe);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id) {
            return (_recipeRepository.GetRecipes()?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [Authorize]
        // POST: Recipes/Approve
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Approve(int id) {
            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }
            _recipeRepository.Approve(recipe);
            return RedirectToAction("Index", "Dashboard");
        }

        [Authorize]
        // POST: Recipes/Deny
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deny(int id, string message) {
            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }
            string responseMessage = message;
            //await DeleteFromFirebaseStorage(recipe.ImgPath);
            _recipeRepository.Deny(recipe, responseMessage);
            return RedirectToAction("Index", "Dashboard");
        }

        private async Task DeleteFromFirebaseStorage(string fileName) {
            if (!string.IsNullOrEmpty(fileName)) {
                string exactFileName = GetImageNameFromUrl(fileName);
                FirebaseAuthProvider firebaseConfiguration = new FirebaseAuthProvider(new FirebaseConfig(ApiKey));
                FirebaseAuthLink authConfiguration = await firebaseConfiguration
                    .SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);

                FirebaseStorage storage = new FirebaseStorage(
                    Bucket,
                    new FirebaseStorageOptions {
                        AuthTokenAsyncFactory = () => Task.FromResult(authConfiguration.FirebaseToken),
                        ThrowOnCancel = true
                    });

                await storage
                    .Child("images")
                    .Child("recipes")
                    .Child(exactFileName) // Use the fileName directly as the child reference
                    .DeleteAsync();

                firebaseConfiguration.Dispose();
            }
        }

        public static string GetImageNameFromUrl(string url) {
            int lastSeparatorIndex = url.LastIndexOf("%2F"); // Get the index of the last "%2F"
            int startIndex = lastSeparatorIndex + 3; // Start index of the desired string
            int endIndex = url.IndexOf("?alt", startIndex); // End index of the desired string
            string extractedString = url.Substring(startIndex, endIndex - startIndex); // Extract the string between the last "%2F" and before "?alt"
            string decodedString = System.Web.HttpUtility.UrlDecode(extractedString); // Decode the extracted string
            return decodedString;
        }
    }
}

CapstoneProject/Views/Shared/_AdminLayout.cshtml
@{
    var currentController = ViewContext.RouteData.Values["Controller"] as string;
    var currentAction = ViewContext.RouteData.Values["Action"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap-5.3.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="icon" type="image/x-icon" href="\images\logo.png">
    <link rel="stylesheet" href="~/css/togglestyle.css" />
    <script src="https://kit.fontawesome.com/08194921a9.js" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet" />
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>
    <style>
        hr {
            clear: both;
            visibility: hidden;
        }

        li {
            list-style: none;
        }

        .list-group-flush .active {
            background-color: black !important;
        }

        .breadcrumb a {
            text-decoration: none;
            font-weight: bold;
            color: cadetblue;
        }

        .breadcrumb {
            margin-bottom: 0;
        }

        @@media screen and (min-width: 991.98px) {
            main {
                padding-left: 240px;
            }
        }

        /* Sidebar */
        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            padding: 88px 0 0; /* Height of navbar */
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
            width: 240px;
            z-index: 600;
        }

        @@media screen and (max-width: 991.98px) {
            .sidebar {
                width: 100%;
            }
        }

        .sidebar .active {
            border-radius: 5px;
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: 0.5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }
    </style>
</head>
<body class="dark">
    @*<div class="container-fluid d-flex d-inline-flex">
    <nav id="sidebarMenu"
    class="collapse d-lg-block sidebar collapse bar-admin-change">
    <div class="position-sticky">
    <div class="list-group list-group-flush mx-3 mt-4">
    <a asp-controller="Dashboard" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "Dashboard" ? "active" : "")"
    aria-current="true">
    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
    </a>
    <a asp-controller="Recipes" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "Recipes" ? "active" : "")">
    <i class="fas fa-chart-area fa-fw me-3"></i><span>Recipes</span>
    </a>
    <a asp-controller="RecipeCategory" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "RecipeCategory" ? "active" : "")">
    <i class="fas fa-chart-area fa-fw me-3"></i><span>Recipe Categories</span>
    </a>
    <a asp-controller="Ingredients" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "Ingredients" ? "active" : "")">
    <i class="fas fa-lock fa-fw me-3"></i><span>Ingredients</span>
    </a>
    <a asp-controller="IngredientCategory" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "IngredientCategory" ? "active" : "")">
    <i class="fas fa-lock fa-fw me-3"></i><span>Ingredient Categories</span>
    </a>
    <a asp-controller="AppRoles" asp-action="Index"
    class="list-group-item list-group-item-action py-2 ripple @(currentController == "AppRoles" ? "active" : "")">
    <i class="fas fa-chart-line fa-fw me-3"></i><span>Roles</span>
    </a>
    </div>
    </div>
    </nav>
    <div class="container-fluid">
    <partial name="_Notification" />
    <breadcrumb class="mt-3 mb-0"></breadcrumb>
    @RenderBody()
    </div>
    </div>*@
    <!--Main Navigation-->
    <header>
        <!-- Sidebar -->
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bar-admin-change">
            <div class="position-sticky">
                <div class="list-group list-group-flush mx-3 mt-4">
                    <a asp-controller="Dashboard" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "Dashboard" ? "active" : "")"
                       aria-current="true">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
                    </a>
                    <a asp-controller="Recipes" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "Recipes" ? "active" : "")">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Recipes</span>
                    </a>
                    <a asp-controller="RecipeCategory" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "RecipeCategory" ? "active" : "")">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Recipe Categories</span>
                    </a>
                    <a asp-controller="Ingredients" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "Ingredients" ? "active" : "")">
                        <i class="fas fa-lock fa-fw me-3"></i><span>Ingredients</span>
                    </a>
                    <a asp-controller="IngredientCategory" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "IngredientCategory" ? "active" : "")">
                        <i class="fas fa-lock fa-fw me-3"></i><span>Ingredient Categories</span>
                    </a>
                    <a asp-controller="AppRoles" asp-action="Index"
                       class="list-group-item list-group-item-action py-2 ripple @(currentController == "AppRoles" ? "active" : "")">
                        <i class="fas fa-chart-line fa-fw me-3"></i><span>Roles</span>
                    </a>
                </div>
            </div>
        </nav>
        <!-- Sidebar -->
        <!-- Navbar -->
        <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Navbar brand -->
                <a class="navbar-brand mt-2 mt-lg-0" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="\images\logo.png"
                         height="80"
                         alt="Cookez Logo"
                         loading="lazy" />
                </a>

                <!-- Toggle button -->
                <button class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse container-fluid justify-content-between text-center" id="navbarSupportedContent">
                    <!-- Search -->
                    <form class="d-flex form-outline pb-2" asp-controller="UserRecipes" asp-action="Filter">
                        <input type="search"
                               class="form-control rounded border"
                               id="SearchString"
                               name="SearchString"
                               placeholder="What do you want to eat today?"
                               aria-label="Search"
                               aria-describedby="search-addon" value="@ViewData["FilterSearch"]" />
                        <button class="btn btn-dark ms-2 rounded" type="submit" value="Find"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>

                    <div class="d-flex justify-content-between">
                        <div class="load-flash"></div>
                        <div class="mode-toggle noselect">
                            <h6 class="label-dark m-0">Dark</h6>
                            <div class="toggle-switch"></div>
                            <h6 class="label-light m-0">Light</h6>
                        </div>

                        <div class="d-flex">
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
    </header>
    <!--Main Navigation-->
    <!--Main layout-->
    <main style="margin-top: 80px;">
        <div class="container pt-4">
            <partial name="_Notification" />
            <breadcrumb class="mt-3 mb-0"></breadcrumb>
            @RenderBody()
        </div>
    </main>
    <!--Main layout-->
    <script src="~/lib/jquery-3.7.0.min.js"></script>
    <script src="~/lib/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/js/togglescript.js"></script>
    <partial name="_ValidationScriptsPartial" />
</body>
</html>

CapstoneProject/Views/Shared/_FavouriteListPartial.cshtml
@model IEnumerable<BusinessObjects.Models.Favourite>
@if ((Model != null)&&(Model.Count()>0)) {
    @foreach (var item in Model) {
        <div class="form-check my-5">
            <label class="control control-checkbox text-color-change">
                @item.Name
                <input class="form-check-input favourite-checkbox" type="checkbox" checked="checked" id="favourite-checkbox-@item.Id" value="@item.Id" />
                <div class="control_indicator"></div>
            </label>
        </div>
    }
}
else{
    <div>You have no collections!</div>
}

CapstoneProject/Views/Shared/_FavouriteModalPartial.cshtml
<div class="favourite-modal modal fade" id="favouriteModal" tabindex="-1" aria-labelledby="favouriteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-color-change">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="favouriteModalLabel"><i class="fa fa-heart mx-1" style="color:red"></i>Add to Collections</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row mb-3" style="height: 64px;">
                    <div class="col-3" style="height:100%">
                        <img id="favourite-recipe-image" src="" class="img-fluid" alt="Food" style="height: 100%; width: 100%;object-fit: cover;">
                    </div>
                    <div class="col-9 text-center" id="favourite-recipe-name" style="font-size:24px">
                    </div>
                </div>
                <div class="mb-3">
                    Please check all the collections you want this recipe to be added
                </div>
                <div class="container list-container" style="">
                    <div class="overflow-auto" style="max-height:100%">
                        <div style="margin-left:1%">
                            <button class="btn btn-white" id="create-collection-button"><i class="fa-solid fa-plus"></i> Create a new Collection</button>
                            <div id="create-collection-form" style="display:none">
                            Name:
                            <input type="text" id="create-collection-name"/>
                                <button class="btn btn-success" id="create-confirm-button">Create</button>
                            </div>
                        </div>
                        <div id="favourite-list-div">

                            @if (ViewBag.FavouriteList != null)
                            {
                                var favourites = ViewData["FavouriteList"] as IEnumerable<Favourite>;
                                <partial name="_FavouriteListPartial" model="@favourites" />
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="favourite-save" type="button" class="btn btn-primary" data-bs-dismiss="modal" data-recipe-id="0">Save</button>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery-3.7.0.min.js"></script>
<script>
    $('#create-collection-button').click(function () {
        $('#create-collection-button').css("display", "none");
        $('#create-collection-form').css("display", "block");
    });
    $('#create-confirm-button').click(function () {
        var name = $("#create-collection-name").val().trim();
        if(name!="") {
            var recipeId = $("#favourite-save").data('recipe-id');
            $('#create-collection-button').css("display", "block");
            $('#create-collection-form').css("display", "none");
            $.ajax({
                url: '/Favourites/CreateAjax',
                type: 'POST',
                data: { name: name },
                success: function (data) {
                    $('#favourite-list-div').html(data);
                    $("#create-collection-name").val('');
                    UpdateCheckbox(recipeId);
                    toastr.success("Create collection successfully!");
                },
                error: function () {
                    toastr.error("Fail to create collection!");
                }
            });
        }
        else {
            toastr.error("Collection name cannot be blank!");
        }
    });
</script>

CapstoneProject/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}