CapstoneProject/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Firebase.Auth;
using Firebase.Storage;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Formats.Webp;
using Microsoft.AspNetCore.WebUtilities;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using MailKit;
using System.Text.RegularExpressions;
using NuGet.Packaging;
using SmartBreadcrumbs.Attributes;
using Microsoft.AspNetCore.Identity;
using BusinessObjects.Models;
using Repositories;

namespace CapstoneProject.Controllers {


    [Authorize(Roles = "Admin")]
    public class RecipesController : Controller {
        private readonly UserManager<Account> _userManager;

        private readonly IRecipeRepository _recipeRepository;
        private readonly IRecipeCategoryRepository _recipeCategoryRepository;

        public static string ApiKey = "AIzaSyDIXdDdvo8NguMgxLvn4DWMNS-vXkUxoag";
        public static string Bucket = "cookez-cloud.appspot.com";
        public static string AuthEmail = "cookez.mail@gmail.com";
        public static string AuthPassword = "cookez";

        public RecipesController(UserManager<Account> userManager, IRecipeRepository recipeRepository, IRecipeCategoryRepository recipeCategoryRepository) {
            _userManager = userManager;
            _recipeRepository = recipeRepository;
            _recipeCategoryRepository = recipeCategoryRepository;
        }

        // GET/POST: Recipes
        [Breadcrumb("Recipes Management")]

        public IActionResult Index(int pg = 1) {
            var recipes = _recipeRepository.GetRecipes();

            const int pageSize = 10; 

            if (pg < 1)
                pg = 1;

            int recsCount = recipes.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = recipes.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data);
        }

        // GET: Recipes/Details/5
        public IActionResult Details(int? id) {

            if (id == null || _recipeRepository.GetRecipes() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            return View(recipe);
        }

        [Authorize]
        // GET: Recipes/Delete/5
        public IActionResult Delete(int? id) {
            if (id == null || _recipeRepository.GetRecipes() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }

            return View(recipe);
        }
        [Authorize]
        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (_recipeRepository.GetRecipes() == null) {
                return Problem("Entity set 'RecipeOrganizerContext.Recipes'  is null.");
            }

            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe != null) {
                if (recipe.ImgPath != null) {
                    await DeleteFromFirebaseStorage(recipe.ImgPath);
                }
                _recipeRepository.DeleteRecipe(recipe);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id) {
            return (_recipeRepository.GetRecipes()?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [Authorize]
        // POST: Recipes/Approve
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Approve(int id) {
            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }
            _recipeRepository.Approve(recipe);
            return RedirectToAction("Index", "Dashboard");
        }

        [Authorize]
        // POST: Recipes/Deny
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deny(int id, string message) {
            var recipe = _recipeRepository.GetRecipeById(id);
            if (recipe == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested recipe was not found." });
            }
            string responseMessage = message;
            //await DeleteFromFirebaseStorage(recipe.ImgPath);
            _recipeRepository.Deny(recipe, responseMessage);
            return RedirectToAction("Index", "Dashboard");
        }

        private async Task DeleteFromFirebaseStorage(string fileName) {
            if (!string.IsNullOrEmpty(fileName)) {
                string exactFileName = GetImageNameFromUrl(fileName);
                FirebaseAuthProvider firebaseConfiguration = new FirebaseAuthProvider(new FirebaseConfig(ApiKey));
                FirebaseAuthLink authConfiguration = await firebaseConfiguration
                    .SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);

                FirebaseStorage storage = new FirebaseStorage(
                    Bucket,
                    new FirebaseStorageOptions {
                        AuthTokenAsyncFactory = () => Task.FromResult(authConfiguration.FirebaseToken),
                        ThrowOnCancel = true
                    });

                await storage
                    .Child("images")
                    .Child("recipes")
                    .Child(exactFileName) // Use the fileName directly as the child reference
                    .DeleteAsync();

                firebaseConfiguration.Dispose();
            }
        }

        public static string GetImageNameFromUrl(string url) {
            int lastSeparatorIndex = url.LastIndexOf("%2F"); // Get the index of the last "%2F"
            int startIndex = lastSeparatorIndex + 3; // Start index of the desired string
            int endIndex = url.IndexOf("?alt", startIndex); // End index of the desired string
            string extractedString = url.Substring(startIndex, endIndex - startIndex); // Extract the string between the last "%2F" and before "?alt"
            string decodedString = System.Web.HttpUtility.UrlDecode(extractedString); // Decode the extracted string
            return decodedString;
        }
    }
}

CapstoneProject/Controllers/UserRecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System.Collections;
using Microsoft.IdentityModel.Tokens;
using SmartBreadcrumbs.Attributes;
using NuGet.Packaging;
using Firebase.Auth;
using Firebase.Storage;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats;
using System.Xml.Linq;
using SixLabors.ImageSharp.Formats.Webp;
using Microsoft.AspNetCore;
using System.Globalization;
using Repositories;
using BusinessObjects.Models;
using Org.BouncyCastle.Utilities;

namespace CapstoneProject.Controllers {

    public class UserRecipesController : Controller {

        private readonly UserManager<Account> _userManager;
        private readonly IRecipeRepository _recipeRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly IRecipeCategoryRepository _recipeCategoryRepository;
        private readonly IFavouriteRepository _favouriteRepository;
        private readonly IRecipeFeedbackRepository _feedbackRepository;
        private readonly IIngredientCategoryRepository _ingredientCategoryRepository;
        private readonly IIngredientRepository _ingredientRepository;

        public static string ApiKey = "AIzaSyDIXdDdvo8NguMgxLvn4DWMNS-vXkUxoag";
        public static string Bucket = "cookez-cloud.appspot.com";
        public static string AuthEmail = "cookez.mail@gmail.com";
        public static string AuthPassword = "cookez";
        public UserRecipesController(
            UserManager<Account> userManager,
            IRecipeRepository recipeRepository,
            IRecipeCategoryRepository recipeCategoryRepository,
            IAccountRepository accountRepository,
            IFavouriteRepository favouriteRepository,
            IRecipeFeedbackRepository feedbackRepository,
            IIngredientCategoryRepository ingredientCategoryRepository,
            IIngredientRepository ingredientRepository) {
            _userManager = userManager;
            _recipeRepository = recipeRepository;
            _accountRepository = accountRepository;
            _recipeCategoryRepository = recipeCategoryRepository;
            _favouriteRepository = favouriteRepository;
            _feedbackRepository = feedbackRepository;
            _ingredientCategoryRepository = ingredientCategoryRepository;
            _ingredientRepository = ingredientRepository;
        }

        [HttpPost]
        public JsonResult AutoComplete(string term) {
            var result = (_recipeRepository.GetRecipes().Where(t => t.Name.ToLower().Contains(term.ToLower()))
                 .Select(t => new { t.Name }))
                 .ToList();
            return Json(result);
        }

        private List<SelectListItem> GetDifficultyList() {
            return new List<SelectListItem>
                    {
                    new SelectListItem { Text = "Easy", Value = "1"},
                    new SelectListItem { Text = "Medium", Value = "2"},
                    new SelectListItem { Text = "Hard", Value = "3"},
                    };
        }
        private List<SelectListItem> GetPrepTimeList() {
            var list = new List<SelectListItem>();
            for (int i = 5; i < 30; i += 5) {
                list.Add(new SelectListItem { Text = i + " minutes", Value = i.ToString() });
            }
            for (int i = 30; i <= 360; i += 30) {
                list.Add(new SelectListItem { Text = i + " minutes", Value = i.ToString() });
            }
            for (int i = 420; i <= 720; i += 60) {
                list.Add(new SelectListItem { Text = i / 60 + " hours", Value = i.ToString() });
            }
            return list;
        }
        private List<SelectListItem> GetUnitsofMeasureList() {
            return new List<SelectListItem>
                    {
                    new SelectListItem { Text = "milliliters", Value = "milliliters"},
                    new SelectListItem { Text = "grams", Value = "grams"},
                    };
        }
        // GET: Recipes
        [Breadcrumb("Recipes")]
        public async Task<IActionResult> Index(int pg = 1) {
            const int pageSize = 6; // Number of recipes in 1 page
            if (pg < 1)
                pg = 1;
            var recipes = _recipeRepository.GetRecipesIndex();
            if (recipes != null) {
                string? searchString = Request.Query["SearchString"];
                string? prepTime = Request.Query["PrepTime"];
                string? recipeCategory = Request.Query["RecipeCategory"];
                string? difficulty = Request.Query["Difficulty"];
                string? sortBy = Request.Query["SortBy"];
                string? includeList = Request.Query["IncludeList"];
                string? excludeList = Request.Query["ExcludeList"];

                //Add all recipecategories
                if (String.IsNullOrEmpty(prepTime))
                    prepTime = "All";
                if (String.IsNullOrEmpty(difficulty))
                    difficulty = "All";
                if (String.IsNullOrEmpty(recipeCategory))
                    recipeCategory = "All";
                if (String.IsNullOrEmpty(sortBy))
                    sortBy = "SortPopular";
                ViewBag.FkRecipeCategoryId = new SelectList(_recipeCategoryRepository.GetRecipeCategories(), "Id", "Name", recipeCategory);
                ViewBag.PrepTime = new SelectList(GetPrepTimeList(), "Value", "Text", prepTime);
                ViewBag.Difficulty = new SelectList(GetDifficultyList(), "Value", "Text", difficulty);
                ViewBag.SortBy = new SelectList(
                new List<SelectListItem>
                {
                new SelectListItem { Text = "Popularity", Value = "SortPopular"},
                new SelectListItem { Text = "Name", Value = "SortName"},
                new SelectListItem { Text = "Newest", Value = "SortNewest"},
                new SelectListItem { Text = "Oldest", Value = "SortOldest"},
                new SelectListItem { Text = "Preparation time", Value = "SortPrepTime"},
                }
                , "Value", "Text", sortBy);

                //View Data
                ViewData["FilterSearch"] = searchString;
                ViewData["FilterPrepTime"] = prepTime;
                ViewData["FilterDifficulty"] = difficulty;
                ViewData["FilterIncludeList"] = includeList;
                ViewData["FilterExcludeList"] = excludeList;
                //Include Ingredients
                if (!prepTime.Equals("All")) {
                    recipes = recipes.Where(b => b.PrepTime <= int.Parse(prepTime));
                }
                if (!difficulty.Equals("All")) {
                    recipes = recipes.Where(b => b.Difficult == int.Parse(difficulty));
                }
                if (!recipeCategory.Equals("All")) {
                    recipes = recipes.Where(b => b.FkRecipeCategoryId == int.Parse(recipeCategory));
                }
                if (!String.IsNullOrEmpty(searchString)) {
                    recipes = recipes.Where(b => b.Name.ToLower().Contains(searchString.ToLower()));
                }
                //Sort
                switch (sortBy) {
                    case "SortOldest":
                        recipes = recipes.OrderBy(b => b.CreatedDate);
                        break;
                    case "SortNewest":
                        recipes = recipes.OrderByDescending(b => b.CreatedDate);
                        break;
                    case "SortPrepTime":
                        recipes = recipes.OrderBy(b => b.PrepTime);
                        break;
                    case "SortName":
                        recipes = recipes.OrderBy(b => b.Name);
                        break;
                    default: // Sort by most popular
                        recipes = recipes.OrderByDescending(b => b.ViewCount);
                        break;
                }
                if (!String.IsNullOrEmpty(includeList)) {
                    var ingredientsList = includeList.Split(',');
                    ViewBag.IncludeList = ingredientsList;
                    foreach (var item in ingredientsList) {
                        recipes = recipes.Where(b => b.Ingredients.Any(i => i.Name.Equals(item)));
                    }
                } else
                    ViewBag.IncludeList = new List<String>();
                //Exclude
                if (!String.IsNullOrEmpty(excludeList)) {
                    var ingredientsList = excludeList.Split(',');
                    ViewBag.ExcludeList = ingredientsList;
                    foreach (var item in ingredientsList) {
                        recipes = recipes.Where(b => b.Ingredients.All(i => !i.Name.Equals(item)));
                    }
                } else
                    ViewBag.ExcludeList = new List<String>();

                //Favourite list
                var currentUser = await _userManager.GetUserAsync(User);
                if (currentUser != null)
                    ViewData["FavouriteList"] = _favouriteRepository.GetFavouritesUserProfile(currentUser);
                else
                    ViewData["FavouriteList"] = null;

                int recsCount = recipes.Count();

                var pager = new Pager(recsCount, pg, pageSize, includeList, excludeList, recipeCategory, prepTime, difficulty, sortBy);

                int recSkip = (pg - 1) * pageSize;

                var data = recipes.Skip(recSkip).Take(pager.PageSize).ToList();

                ViewData["count"] = recsCount;

                this.ViewBag.Pager = pager;

CapstoneProject/Views/Recipes/Delete.cshtml
@model BusinessObjects.Models.Recipe

@{
    ViewBag.Title = "Create recipe";
    //Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImgPath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.Raw(Model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nutrition)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nutrition)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrepTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Difficult)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Difficult)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FkUserId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FkUserId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FkRecipe)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FkRecipe.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FkRecipeCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FkRecipeCategory.Name)
        </dd>
    </dl>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-danger" /> 
    <a asp-action="Index" class="btn btn-warning ms-2">Back to List</a>
</form>

CapstoneProject/Views/Recipes/Index.cshtml
@model IEnumerable<BusinessObjects.Models.Recipe>

@inject SignInManager<Account> SignInManager
@using Microsoft.AspNetCore.Identity;
@inject UserManager<Account> UserManager

@{
    ViewBag.Title = "View Recipe";
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null) {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*
        <form class="form-inline" asp-controller="Recipes" asp-action="Search">
        <input class="form-control mr-sm-2" id="searchString" name="searchString" type="text" placeholder="Search" aria-label="Search" value="@ViewData["FilterSearch"]" />
        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search" />
    </form>
    <div class="row">
        <div class="px-0">
            <br />
            <div class="col-5">
                <a asp-controller="Recipes" asp-action="Create" class="btn btn-success fw-bold text-light mt-2"><i class="fa-solid fa-folder-plus"></i> New Recipes</a>
            </div>
            <br />
            <div class="container row">
                <div class="col-sm-2">
                    <form id="formFilter" name="formFilter" class="form-inline" asp-controller="Recipes" asp-action="Filter">

                        <input class="form-control mr-sm-2" id="includeIngredients" name="includeIngredients" type="text" placeholder="Include Ingredients" />
                        <label class="form-label d-none" for="includeIngredients">Include Ingredients:</label>

                        <label for="recipeCategory" class="control-label">Recipe Category:</label>
                        <select class="form-control" name="recipeCategory" asp-items="ViewBag.FkRecipeCategoryId" onchange="document.getElementById('btnSubmit').click();">
                            <option value="All">All</option>
                        </select>
                        <label for="prepTime" class="form-label">PrepTime:</label>
                        <select class="form-select" name="prepTime" onchange="document.getElementById('btnSubmit').click();">
                            <option value="All">All</option>
                            @for (var i = 5; i < 30; i += 5)
                            {
                                @if (!(String.IsNullOrEmpty(@ViewData["FilterPrepTime"].ToString())) && (@ViewData["FilterPrepTime"].Equals(i.ToString())))
                                {
                                    <option value="@i" selected>0 - @i</option>
                                }
                                else
                                {
                                    <option value="@i">0 - @i</option>
                                }
                            }
                        </select>
                        <label for="difficulty" class="form-label">Difficulty:</label>
                        <select class="form-select" name="difficulty" onchange="document.getElementById('btnSubmit').click();">
                            <option value="All">All</option>
                            @for (var i = 1; i < 6; i++)
                            {
                                @if (!(String.IsNullOrEmpty(@ViewData["FilterDifficulty"].ToString())) && (@ViewData["FilterDifficulty"].Equals(i.ToString())))
                                {
                                    <option value="@i.ToString()" selected>@i.ToString()</option>
                                }
                                else
                                {
                                    <option value="@i.ToString()">@i.ToString()</option>
                                }
                            }
                        </select>
                        <input id="SearchString" name="searchString" type="hidden" value="@ViewData["FilterSearch"]" />
                        <input type="submit" hidden id="btnSubmit" value="Filter" />
                    </form>
                </div>
    *@
<br />
<br />

<div class="container-fluid">
    <table class="table table-bordered table-striped w-auto">
        <thead class="table-dark">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    ImgPath
                </th>
                <th>
                    PrepTime
                </th>
                <th>
                    Difficulty
                </th>
                <th>
                    Owner
                </th>
                <th>
                    CreatedDate
                </th>
                <th>
                    Category
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="p-0" style="width: 12%;">
                        <img src="@item.ImgPath" class="img-fluid w-100" style="max-height: 150px;">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrepTime)
                    </td>

                    <td>
                        @if (item.Difficult == 1) {
                            <p class="text-color-change">Easy</p>
                        } else if (item.Difficult == 2) {
                            <p class="text-color-change">Medium</p>
                        } else if (item.Difficult == 3) {
                            <p class="text-color-change">Hard</p>
                        }
                    </td>
                    <td>
                        @item.FkUser?.UserName
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FkRecipeCategory.Name)
                    </td>
                    <td>
                        <a asp-controller="UserRecipes" asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirm-@item.Id">Delete</button>
                        <!-- Modal -->
                        <div class="modal fade" id="deleteConfirm-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Delete</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true"></span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form id="deleteConfirmForm-@item.Id" asp-action="Delete">
                                            <input type="hidden" name="id" value="@item.Id" />
                                            <h6>@item.Name</h6>
                                            <p>Are you sure you want to delete this recipe?</p>
                                        </form>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button class="btn btn-danger submitDeleteFormBtn" data-modal-id="deleteConfirm-@item.Id">Confirm</button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
<partial name="_Pager" model="@pager" />
</div>
<script src="~/lib/jquery-3.7.0.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
<script>
    $(document).ready(function () {
        // Click event for "Delete" buttons with class deleteConfirmModalBtn
        $(".deleteConfirmModalBtn").click(function () {
            // Get the ID of the modal associated with this button
            var modalId = $(this).data("modal-id");

            // Show the modal using the Bootstrap modal method
            $("#" + modalId).modal("show");
        });

        // Click event for "Confirm" buttons inside the modals
        $(".modal").on("click", ".submitDeleteFormBtn", function () {
            // Find the form inside the current modal
            var form = $(this).closest(".modal-content").find("form");

            // Submit the form
            form.submit();
        });
    });
</script>