CapstoneProject/Controllers/FavouritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using SmartBreadcrumbs.Attributes;
using Microsoft.AspNetCore.Authorization;
using Repositories;
using BusinessObjects.Models;

namespace CapstoneProject.Controllers {

    public class FavouritesController : Controller {

        private readonly IFavouriteRepository _favouriteRepository;
        private readonly IRecipeRepository _recipeRepository;
        private readonly UserManager<Account> _userManager;

        public FavouritesController(IFavouriteRepository favouriteRepository, IRecipeRepository recipeRepository, UserManager<Account> userManager) {
            _favouriteRepository = favouriteRepository;
            _recipeRepository = recipeRepository;
            _userManager = userManager;
        }

        //These codes are used in Favourites/Details
        [HttpPost]
        public async Task<JsonResult> AddToFavourite(int favouriteId, int recipeId) {
            var favouriteList = _favouriteRepository.GetFavouriteById(favouriteId);
            var recipe = _recipeRepository.GetRecipeById(recipeId);
            _favouriteRepository.InsertRecipeToFavourite(favouriteList, recipe);
            return Json(true);
        }
        [HttpPost]
        public async Task<JsonResult> RemoveFromFavourite(int favouriteId, int recipeId) {
            var favouriteList = _favouriteRepository.GetFavouriteById(favouriteId);
            var recipe = _recipeRepository.GetRecipeById(recipeId);
            _favouriteRepository.DeleteRecipeFromFavourite(favouriteList, recipe);
            return Json(true);
        }


        [HttpPost]
        [Authorize]
        public async Task<JsonResult> AddRecipe(int recipeId, int[] favouriteIds, int[] allfavouriteIds) {
            var entity = _recipeRepository.GetRecipeById(recipeId);
            if (entity != null) {
                foreach (var favouriteId in allfavouriteIds) {
                    var favourite = _favouriteRepository.GetFavouriteById(favouriteId);

                    if ((favouriteIds.Contains(favouriteId)) && (!favourite.Recipes.Select(r => r.Id).Contains(entity.Id))) {
                        _favouriteRepository.InsertRecipeToFavourite(favourite, entity);
                    } else
                    if (!(favouriteIds.Contains(favouriteId)) && (favourite.Recipes.Select(r => r.Id).Contains(entity.Id))) {
                        _favouriteRepository.DeleteRecipeFromFavourite(favourite, entity);
                    }
                }
            }

            return Json(new { success = true });
        }
        [HttpPost]
        public async Task<IActionResult> CreateAjax(string name)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var favourite = new Favourite()
            {
                Name = name,
                Description = null,
                isPrivate = true,
            };
            favourite.Account = currentUser;
            _favouriteRepository.InsertFavourite(favourite);
            var data = _favouriteRepository.GetFavouritesUserProfile(currentUser);
            return PartialView("_FavouriteListPartial", data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,isPrivate")] Favourite favourite) {
            if (ModelState.IsValid) {
                favourite.Account = await _userManager.GetUserAsync(User);
                _favouriteRepository.InsertFavourite(favourite);
                return RedirectToAction(nameof(Index));
            }
            return View(favourite);
        }


        [HttpPost]
        public async Task<JsonResult> GetAllFavouriteRecipes(int[] recipeIds) {
            var favourites = new List<object>();

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null) {
                foreach (var recipeId in recipeIds) {
                    var favorite = _favouriteRepository.GetAllFavouriteRecipes(recipeId, currentUser);
                    if (favorite != null) {
                        favourites.Add(new { recipeId = recipeId, isFavorite = true });
                    } else {
                        favourites.Add(new { recipeId = recipeId, isFavorite = false });
                    }
                }
            }

            return Json(favourites);
        }
        //This is for favourite's checkboxes
        [HttpPost]
        public async Task<JsonResult> GetAllFavouriteLists(int recipeId, int[] favouriteIds) {
            var favourites = new List<object>();

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null) {
                foreach (var favouriteId in favouriteIds) {
                    var favorite = _favouriteRepository.GetAllFavouriteLists(recipeId, favouriteId, currentUser);
                    if (favorite != null) {
                        favourites.Add(new { id = favouriteId, isFavorite = true });
                    } else {
                        favourites.Add(new { id = favouriteId, isFavorite = false });
                    }
                }
            }

            return Json(favourites);
        }


        // GET: Favourites
        [Breadcrumb("My Collections")]
        [Authorize]
        public async Task<IActionResult> Index() {
            var currentUser = await _userManager.GetUserAsync(User);
            var userFavourite = _favouriteRepository.GetFavouritesIndex(currentUser);
            return View(userFavourite);
        }

        // GET: Favourites/Details/5
        [Breadcrumb("Collection Details")]
        public IActionResult Details(int? id) {

            var favouriteList = _favouriteRepository.GetFavouritesDetails(id);

            if (favouriteList == null)
            {
                return NotFound();
            }

            ViewData["Name"] = favouriteList?.Name;
            ViewData["Description"] = favouriteList?.Description;
            ViewData["IsPrivate"] = favouriteList?.isPrivate;
            ViewData["Id"] = id;
            if (favouriteList?.Account != null)
                ViewData["UserId"] = favouriteList.Account.Id;

            var recipes = favouriteList?.Recipes
                .ToList();
            return View(recipes);
        }

        // GET: Favourites/Create
        [Authorize]
        public IActionResult Create() {
            return View();
        }

        // GET: Favourites/Edit/5
        [Authorize]
        public IActionResult Edit(int? id) {
            if (id == null || _favouriteRepository.GetFavourites() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested Favourite was not found." });
            }

            var favourite = _favouriteRepository.GetFavouriteById(id);
            if (favourite == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested Favourite was not found." });
            }
            return View(favourite);
        }


        [HttpPost]
        public async Task<JsonResult> Edit(int id, string name, string description, bool isPrivate) {
            try {
                _favouriteRepository.UpdateFavourite(id, name, description, isPrivate);
            } catch (DbUpdateConcurrencyException) {
                if (!FavouriteExists(id)) {
                    return null;
                } else {
                    throw;
                }
            }
            return Json(new { name = name, description = description, isPrivate = isPrivate });
        }

        // GET: Favourites/Delete/5
        [Authorize]
        public IActionResult Delete(int? id) {
            if (id == null || _favouriteRepository.GetFavourites() == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested Favourite was not found." });
            }

            var favourite = _favouriteRepository.GetFavouriteById(id);
            if (favourite == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested Favourite was not found." });
            }

            return View(favourite);
        }

        // POST: Favourites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (_favouriteRepository.GetFavourites() == null) {
                return Problem("Entity set 'RecipeOrganizerContext.Favourites'  is null.");
            }
            var favourite = _favouriteRepository.GetFavouriteById(id);
            if (favourite != null) {
                _favouriteRepository.DeleteFavourite(favourite);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool FavouriteExists(int id) {
            return (_favouriteRepository.GetFavourites()?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CapstoneProject/Views/Favourites/Create.cshtml
@model Favourite

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-center label-font">New collection</h2>

<hr />
<div style="min-height: 100vh; display: flex; flex-direction: column;">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form id="create-form" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div asp-validation-summary="ModelOnly" class="text-danger text-color-change-red"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label label-font mb-2 mt-2"></label>
                    <input asp-for="Name" class="form-control" placeholder="e.g. Recipes for Lunar new year" required/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label label-font mb-2 mt-2"></label>
                    <input asp-for="Description" class="form-control" placeholder="e.g. My family enjoy these recipes"/>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="isPrivate" class="control-label label-font mb-2 mt-2">Sharing Settings</label>
                    <select asp-for="isPrivate" class="form-control" required>
                        <option value="true">Private</option>
                        <option value="false">Public</option>
                    </select>
                    <span asp-validation-for="isPrivate" class="text-danger"></span>
                </div>
                <div class="form-group mt-3 text-center">
                    <div id="create-button-container" class="position-relative d-inline-block">
                        <input type="submit" value="Create" class="btn btn-success" id="create-button" />
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>

    <div class=" text-center">
        <a asp-action="Index" class="btn btn-warning mt-3">Back to List</a>
    </div>
    <div style="flex-grow:1"></div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CapstoneProject/Views/Favourites/Delete.cshtml
@model BusinessObjects.Models.Favourite

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Favourite</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CapstoneProject/Views/Favourites/Edit.cshtml
@model BusinessObjects.Models.Favourite

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Favourite</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger text-color-change-red"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CapstoneProject/Views/Favourites/Index.cshtml
@model IEnumerable<BusinessObjects.Models.Favourite>

@{
    ViewData["Title"] = "My Collections";
}

<link rel="stylesheet" href="~/css/collection.css" />
<style>
    .card-limit-1 {
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .card-limit-2 {
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .box {
        box-shadow: 0 0 0px rgba(0, 0, 0, 0.5);
        transition: box-shadow 0.3s ease-in-out;
    }

        .box:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 1);
        }

</style>


<div class="container-fluid">
    <div class="row">
        <a asp-action="Create" class="btn btn-success fw-bold mt-4 mb-4 ms-2 col-md-2 col-6">New collection</a>
    </div>
    <div class="row row-cols-1 row-cols-lg-3 gy-5 g-lg-3 dark">
        @if (Model.Count() == 0)
        {
            <div>
                <div class="text-center">
                    <img src="~/images/noresult.png" style="width: 18%; height: auto;">
                    <p class="fw-bold mt-5">Apologies, you don't have any Collection.</p>
                </div>
            </div>
        }
        @foreach (var collection in Model)
        {
            <div class="col" style="text-align: -webkit-center">
                <div class="card box mb-3 collection-card w-80">
                    <div class="card-head card-img-top">
                        <a asp-controller="Favourites" asp-action="Details" asp-route-id="@collection.Id">
                            <div style="height: 100%; width: 100%;">
                                @if (collection.Recipes.FirstOrDefault() != null)
                                {
                                    if (collection.Recipes.First().ImgPath != null)
                                    {
                                        <img src="@collection.Recipes.First().ImgPath" class="img-fluid" alt="Food" style="height: 100%;width: 100%; object-fit: cover;">
                                    }
                                }
                            </div>
                        </a>
                    </div>
                    <div class="card-body" style="padding: 0">
                        <div class="d-none d-md-flex justify-content-around" style="height: 30%;width: 100%; padding: 0; margin: 0;">
                            @for (var i = 0; i < 3; i++)
                            {
                                <div class="col-4" style="height: 100%; width:30%;background-color: darkgray; padding: 0; margin-top: 4px; margin-bottom: 4px">
                                    <a asp-controller="Favourites" asp-action="Details" asp-route-id="@collection.Id">
                                        <div style="height: 100%; width: 100%;">
                                            @if (i + 1 < collection.Recipes.Count())
                                            {
                                                @if (collection.Recipes.ElementAt(1 + i) != null)
                                                {
                                                    @if (collection.Recipes.ElementAt(1 + i).ImgPath != null)
                                                    {
                                                        <img src="@collection.Recipes.ElementAt(1+i).ImgPath" class="img-fluid" alt="Food" style="height: 100%; width: 100%;object-fit: cover;">
                                                    }
                                                }
                                            }
                                        </div>
                                    </a>
                                </div>
                            }
                        </div>
                        <div style="margin: 8px;text-align:left">
                            @{
                                var privacyText = "PUBLIC";
                                if ((bool)collection.isPrivate)
                                    privacyText = "PRIVATE";
                            }
                                <div style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif" class="text-color-change">@privacyText</div>

                            <a class="card-title card-limit-1 link-info link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-color-change"
                               asp-controller="Favourites" asp-action="Details" asp-route-id="@collection.Id">

                                <h5 style="font-weight: bold;" class="text-color-change">@collection.Name</h5>
                            </a>
                            @if (collection.Description == null)
                            {
                                <p class="card-text card-limit-2 text-color-change" style="height:52px">This collection doesn't have a description yet.</p>
                            }
                            else
                            {
                                <p class="card-text card-limit-2" style="height:52px">@collection.Description</p>
                            }

                            <h6 class="card-text card-limit-1">@collection.Recipes.Count() item(s) in this collection</h6>
                        </div>
                    </div>
                </div>
            </div>
        }@*END OF FOREACH*@
    </div>
    <div style="flex-grow:1"></div>
</div>