CapstoneProject/Controllers/IngredientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Firebase.Auth;
using Firebase.Storage;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Formats.Webp;
using Microsoft.AspNetCore.WebUtilities;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using MailKit;
using System.Text.RegularExpressions;
using SmartBreadcrumbs.Attributes;
using BusinessObjects.Models;
using Repositories;

namespace CapstoneProject.Controllers {

    public class IngredientsController : Controller {

        public static string ApiKey = "AIzaSyDIXdDdvo8NguMgxLvn4DWMNS-vXkUxoag";
        public static string Bucket = "cookez-cloud.appspot.com";
        public static string AuthEmail = "cookez.mail@gmail.com";
        public static string AuthPassword = "cookez";

        private readonly IIngredientRepository _ingredientRepository;
        private readonly IIngredientCategoryRepository _ingredientCategoryRepository;

        public IngredientsController(IIngredientRepository ingredientRepository, IIngredientCategoryRepository ingredientCategoryRepository) {
            _ingredientRepository = ingredientRepository;
            _ingredientCategoryRepository = ingredientCategoryRepository;
        }
        [HttpPost]
        public JsonResult AutoComplete(string term)
        {
            var list = _ingredientRepository.GetIngredients();
            var result = (list.Where(i => i.Status == true).Where(t => t.Name.ToLower().Contains(term.ToLower()))
                 .Select(t => new { t.Name }))
                 .ToList();
            return Json(result);
        }

        [Authorize(Roles = "Admin")]
        [Breadcrumb("Ingredients Management")]
        public IActionResult Index() {
            var objIngredient = _ingredientRepository.GetIngredients();
            return View(objIngredient);
        }

        // GET
        [Breadcrumb("Create", FromAction = "Index", FromController = typeof(IngredientsController))]
        [Authorize(Roles = "Admin")]
        public IActionResult Create() {
            ViewData["FkCategoryId"] = new SelectList(_ingredientCategoryRepository.GetIngredientCategories(), "Id", "Name");
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Ingredient model) {
            if (ModelState.IsValid) {
                if (model.file != null && model.file.Length > 0) {
                    IFormFile file = model.file;
                    // Generate a unique file name
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                    // Upload the file to Firebase Storage
                    string imageUrl = await UploadFirebase(file.OpenReadStream(), uniqueFileName);
                    Uri imageUrlUri = new Uri(imageUrl);
                    string baseUrl = $"{imageUrlUri.GetLeftPart(UriPartial.Path)}?alt=media";
                    model.ImgPath = baseUrl;
                    model.Status = true;
                    _ingredientRepository.InsertIngredient(model);
                    TempData["success"] = "Ingredient created successfully";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateAjax(Ingredient model) {
            if (ModelState.IsValid) {
                if (model.file != null && model.file.Length > 0) {
                    IFormFile file = model.file;
                    // Generate a unique file name
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                    // Upload the file to Firebase Storage
                    string imageUrl = await UploadFirebase(file.OpenReadStream(), uniqueFileName);
                    Uri imageUrlUri = new Uri(imageUrl);
                    string baseUrl = $"{imageUrlUri.GetLeftPart(UriPartial.Path)}?alt=media";
                    model.ImgPath = baseUrl;
                    model.Status = false;
                    _ingredientRepository.InsertIngredient(model);
                    TempData["success"] = "Ingredient created successfully";
                    return Json(new { success = true });
                }
            }

            return Json(new { success = false });
        }

        // GET: Ingredient/Detail/id
        [Authorize(Roles = "Admin")]
        public IActionResult Detail(int? id) {
            if (id == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            var ingredient = _ingredientRepository.GetIngredientById(id);

            if (ingredient == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            return View(ingredient);
        }


        public static async Task<string> UploadFirebase(Stream stream, string fileName) {
            string imageFromFirebaseStorage = "";
            using (Image image = Image.Load(stream)) {

                // Resize the image to a smaller size if needed
                int maxWidth = 1000; // Set your desired maximum width here
                int maxHeight = 1000; // Set your desired maximum height here
                if (image.Width > maxWidth || image.Height > maxHeight) {
                    image.Mutate(x => x.Resize(new ResizeOptions {
                        Size = new Size(maxWidth, maxHeight),
                        Mode = ResizeMode.Max
                    }));
                }

                using (MemoryStream webpStream = new()) {

                    await image.SaveAsync(webpStream, new WebpEncoder());

                    webpStream.Position = 0;

                    FirebaseAuthProvider firebaseConfiguration = new(new FirebaseConfig(ApiKey));

                    FirebaseAuthLink authConfiguration = await firebaseConfiguration
                        .SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);

                    CancellationTokenSource cancellationToken = new();

                    FirebaseStorageTask storageManager = new FirebaseStorage(
                        Bucket,
                        new FirebaseStorageOptions {
                            AuthTokenAsyncFactory = () => Task.FromResult(authConfiguration.FirebaseToken),
                            ThrowOnCancel = true
                        })
                        .Child("images")
                        .Child("ingredients")
                        .Child(fileName)
                        .PutAsync(webpStream, cancellationToken.Token);

                    try {
                        imageFromFirebaseStorage = await storageManager;
                        firebaseConfiguration.Dispose();
                        return imageFromFirebaseStorage;
                    } catch (Exception ex) {
                        Console.WriteLine("Exception was thrown: {0}", ex);
                        return null;
                    }
                }
            }
        }


        //GET
        [Breadcrumb("Edit", FromAction = "Index", FromController = typeof(IngredientsController))]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id) {
            if (id == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            var ingredient = _ingredientRepository.GetIngredientById(id);

            if (ingredient == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            ViewData["FkCategoryId"] = new SelectList(_ingredientCategoryRepository.GetIngredientCategories(), "Id", "Name");
            return View(ingredient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id, [Bind("Id, Name, ImgPath, Description, Status, FkCategoryId")] Ingredient ingredient) {
            if (id != ingredient.Id) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            if (ModelState.IsValid) {
                try {
                    _ingredientRepository.UpdateIngredient(ingredient);
                    TempData["success"] = "Ingredient updated successfully";
                } catch (Exception) {
                    return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
                }
                return RedirectToAction("Index");
            }

            ViewData["FkCategoryId"] = new SelectList(_ingredientCategoryRepository.GetIngredientCategories(), "Id", "Name");
            return View(ingredient);
        }

        private bool IngredientExists(int id) {
            return (_ingredientRepository.GetIngredients()?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        // GET
        [Breadcrumb("Delete", FromAction = "Index", FromController = typeof(IngredientsController))]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id) {
            if (id == null) {
                return RedirectToAction("NotFound", "Error", new { errorMessage = "The requested ingredient was not found." });
            }

            var ingredient = _ingredientRepository.GetIngredientById(id);

            if (ingredient == null) {

CapstoneProject/Views/Ingredients/Create.cshtml
@model BusinessObjects.Models.Ingredient

@{
    ViewData["Title"] = "Create ingredient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post" enctype="multipart/form-data">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-success">Create Ingredient</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label class="mb-2" asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="mb-2" asp-for="file">Upload File</label>
            <input asp-for="file" class="form-control" type="file" name="file" accept="image/png, image/jpeg" required />
        </div>
        <div class="mb-3">
            <label class="mb-2" asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="FkCategoryId" class="control-label">Select category</label>
            <select asp-for="FkCategoryId" class="form-control" asp-items="ViewBag.FkCategoryId"></select>
        </div>
        <p>Nutrition Facts (Per 1 grams/milliliters)</p>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Calories"></label>
            <input asp-for="IngredientNutrition.Calories" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Fibre"></label>
            <input asp-for="IngredientNutrition.Fibre" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Carbohydrate"></label>
            <input asp-for="IngredientNutrition.Carbohydrate" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Protein"></label>
            <input asp-for="IngredientNutrition.Protein" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Fat"></label>
            <input asp-for="IngredientNutrition.Fat" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="mb-2" asp-for="IngredientNutrition.Cholesterol"></label>
            <input asp-for="IngredientNutrition.Cholesterol" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-3" style="width: 10%;">Create</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-warning mt-3" style="width: 10%;">Back to list</a>
    </div>
</form>

CapstoneProject/Views/Ingredients/Delete.cshtml
@model BusinessObjects.Models.Ingredient
@{
    ViewBag.Title = "Delete ingredient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-danger">Are you sure you want to delete this item?</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled/>
        </div>
        <div class="mb-3">
            <label asp-for="ImgPath"></label>
            <input asp-for="ImgPath" class="form-control" disabled/>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" disabled/>
        </div>
        <button type="submit" class="btn btn-danger" style="width: 10%;">Delete</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-warning" style="width: 10%;">Back to list</a>
    </div>
</form>

CapstoneProject/Views/Ingredients/Detail.cshtml
@model BusinessObjects.Models.Ingredient

<form method="post" enctype="multipart/form-data">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-success">Create Ingredient</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label for="name" class="form-label font-weight-bold">Name</label>
            <div class="form-control" id="name">@Model.Name</div>
        </div>
        <div class="mb-3">
            <label for="image">Image</label>
            <div class="mb-3">
                <img src="@Model.ImgPath" class="img-fluid" style="max-width: 200px; height: auto;">
            </div>
        </div>
        <div class="mb-3">
            <label for="description">Description</label>
            <div class="form-control" id="description">@Model.Description</div>
        </div>
        <div class="mb-3">
            <label for="category">Category</label>
            <div class="form-control" id="category">@Model.FkCategory.Name</div>
        </div>

        <!-- Nutrition Details -->
        <div class="mb-3">
            <h4>Nutrition Information</h4>
            <div class="mb-2">
                <label for="calories" class="form-label">Calories</label>
                <div class="form-control" id="calories">@Model.IngredientNutrition.Calories</div>
            </div>
            <div class="mb-2">
                <label for="fiber" class="form-label">Fiber</label>
                <div class="form-control" id="fiber">@Model.IngredientNutrition.Fibre</div>
            </div>
            <div class="mb-2">
                <label for="carbohydrate" class="form-label">Carbohydrate</label>
                <div class="form-control" id="carbohydrate">@Model.IngredientNutrition.Carbohydrate</div>
            </div>
            <div class="mb-2">
                <label for="protein" class="form-label">Protein</label>
                <div class="form-control" id="protein">@Model.IngredientNutrition.Protein</div>
            </div>
            <div class="mb-2">
                <label for="fat" class="form-label">Fat</label>
                <div class="form-control" id="fat">@Model.IngredientNutrition.Fat</div>
            </div>
            <div class="mb-2">
                <label for="cholesterol" class="form-label">Cholesterol</label>
                <div class="form-control" id="cholesterol">@Model.IngredientNutrition.Cholesterol</div>
            </div>
        </div>
    </div>
    <a asp-controller="Dashboard" asp-action="Index" class="btn btn-warning mt-3" style="width: 10%;">Back to dashboard</a>
</form>

CapstoneProject/Views/Ingredients/Edit.cshtml
@model BusinessObjects.Models.Ingredient
@{
    ViewBag.Title = "Edit ingredient info";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger text-color-change-red"></div>
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Ingredient</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3 d-none">
            <label asp-for="ImgPath" class="control-label"></label>
            <input asp-for="ImgPath" class="form-control" />
            <span asp-validation-for="ImgPath" class="text-danger"></span>
        </div>
        <div class="mb-3 d-none">
            <label asp-for="Status" class="control-label"></label>
            <input asp-for="Status" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="FkCategoryId" class="control-label">Category Name</label>
            <select asp-for="FkCategoryId" class="form-control" asp-items="ViewBag.FkCategoryId"></select>
            <span asp-validation-for="FkCategoryId" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 10%;">Update</button>
        <a asp-controller="Ingredients" asp-action="Index" class="btn btn-warning" style="width: 10%;">Back to list</a>
    </div>
</form>

CapstoneProject/Views/Ingredients/Index.cshtml
@model IEnumerable<BusinessObjects.Models.Ingredient>
@{
    ViewBag.Title = "Ingredient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .card-text {
        display: -webkit-box;
        -webkit-line-clamp: 2; /* Maximum number of lines to show */
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>

<div class="container-fluid">
    <div class="px-0">
        <br />
        <div class="col-5">
            <a asp-controller="Ingredients" asp-action="Create" class="btn btn-success fw-bold text-light mt-2"><i class="fa-solid fa-folder-plus"></i> New Ingredient</a>
        </div>
        <br />
        <table class="table table-striped table-bordered w-100">
            <thead class="table-dark">
                <tr>
                    <th style="width: 11%;">
                        Name
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Description
                    </th>
                    <th style="width: 8%;">
                        Category
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="p-0">
                            <img src="@Html.DisplayFor(modelItem => item.ImgPath)" style="width: 100px; height: 100px;">
                        </td>
                        <td>
                            <p class="card-text text-color-change">@Html.DisplayFor(modelItem => item.Description)</p>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FkCategory.Name)
                        </td>
                        <td style="width: 1%;">
                            <a class="btn btn-warning text-light" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        </td>
                        <td style="width: 1%;">
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>